Si Ã¨ verificato un errore durante {{action}} le dipendenze Python per {{skill}}.
